# Generated by Django 4.0.4 on 2022-07-31 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_alter_users_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='userss',
        ),
    ]
