# Generated by Django 4.0.4 on 2022-07-31 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_rename_users_userss'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userss',
            new_name='users',
        ),
    ]
